name: Merge upstream

on:
  schedule:
    - cron: "0 0 1 * *" # monthly
  workflow_dispatch:

concurrency:
  group: merge-upstream-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # to push branch
  pull-requests: write # to create pr

jobs:
  merge_upstream:
    uses: SpiralP/github-reusable-workflows/.github/workflows/merge-upstream.yml@8cd236d2625eddac0a5ce3520e49be7be3631079 # main
    with:
      url: https://github.com/SpiralP/github-reusable-workflows.git
