name: Release

on:
  push:
    branches: [master, main]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false # do not cancel in-progress jobs

permissions:
  contents: read # for checkout

jobs:
  get-version-metadata:
    runs-on: ubuntu-24.04
    outputs:
      version-metadata: ${{ steps.get-version-metadata.outputs.version-metadata }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: get-version-metadata
        run: |
          version_metadata="$(git tag --list 'v*.*.*' |wc -l)"
          version_metadata="$(( version_metadata + 1 ))"
          echo "version-metadata=$version_metadata" | tee -a "$GITHUB_OUTPUT"

  release:
    needs: get-version-metadata
    permissions: {} # none, since we use a custom app
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@cb2e4e89a87ce3c5d46955d2f5b2628f1c4745a7 # main
    with:
      environment-name: release
      extends: ./.github/semantic-release.json
      replace-files: |
        Cargo.lock
        Cargo.toml
        package-lock.json
        package.json
      version-metadata: ${{ needs.get-version-metadata.outputs.version-metadata }}
    secrets:
      app-id: ${{ secrets.APP_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}

  deploy:
    needs: release
    runs-on: ubuntu-24.04
    environment:
      name: release
      url: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ needs.release.outputs.tag }}
    steps:
      - run: "true"
