name: Release

on:
  push:
    branches: [master, main]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false # do not cancel in-progress jobs

permissions:
  contents: write # for checkout, and to be able to create a release

jobs:
  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@c98303ee2c53b4f0dd56aa01d33873853488321c # main
    with:
      extends: ./.github/semantic-release.json
