name: release

on:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false # do not cancel in-progress jobs

permissions: {}

jobs:
  get-version-metadata:
    runs-on: ubuntu-24.04
    permissions:
      contents: read # for checkout
    outputs:
      version-metadata: ${{ steps.get-version-metadata.outputs.version-metadata }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive
      - id: get-version-metadata
        run: |
          version_metadata="$(git tag --list 'v*.*.*' |wc -l)"
          test -z "$version_metadata" && echo "version_metadata is empty" && exit 1
          version_metadata="$(( version_metadata + 1 ))"
          echo "version-metadata=$version_metadata" | tee -a "$GITHUB_OUTPUT"

  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@408cb90aab3ba9328f52c6242dc2e5e51514342b # main
    needs: get-version-metadata
    if: ${{ needs.get-version-metadata.outputs.version-metadata }}
    permissions: {} # none, since we use a custom app
    with:
      environment-name: release
      extends: ./.github/semantic-release.json
      replace-files: |
        Cargo.lock
        Cargo.toml
        package-lock.json
        package.json
      version-metadata: ${{ needs.get-version-metadata.outputs.version-metadata }}
    secrets:
      app-id: ${{ secrets.APP_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
