name: Update nix hashes

on:
  pull_request:
    branches: [master, main]

concurrency:
  group: update-nix-hashes-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # to push branch

jobs:
  update_nix_hashes:
    # !!! disabled
    if: ${{ false }}
    uses: SpiralP/github-reusable-workflows/.github/workflows/update-nix-hashes.yml@6a97e79612d1142ba419025da07a8d6c9243e435 # main
    with:
      npm-attribute: node
