name: Update lock files

on:
  schedule:
    - cron: "0 0 1 * *" # monthly
  workflow_dispatch:

concurrency:
  group: update-lock-files-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # to push branch
  pull-requests: write # to create pr

jobs:
  update_lock_files:
    uses: SpiralP/github-reusable-workflows/.github/workflows/update-lock-files.yml@89676213c6d6c21560934473b38469e7fc45be3c # main
    with:
      npm-attribute: node
      rust-attribute: rust
