name: Update nix hashes

on:
  pull_request:
    branches: [ master, main ]

concurrency:
  group: update-nix-hashes-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # to push branch

jobs:
  update_nix_hashes:
    # !!! disabled
    if: ${{ false }}
    uses: SpiralP/github-reusable-workflows/.github/workflows/update-nix-hashes.yml@e0b3d44f57cf1ae85c88decde04c53ad32f0fb36 # main
    with:
      npm-attribute: node
