name: Update nix hashes

on:
  pull_request:
    branches: [ master, main ]

concurrency:
  group: update-nix-hashes-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # to push branch

jobs:
  update_nix_hashes:
    # !!! disabled
    if: ${{ false }}
    uses: SpiralP/github-reusable-workflows/.github/workflows/update-nix-hashes.yml@4b41639a9fc865b20a6a32e51b70555a54759db0 # main
    with:
      npm-attribute: node
